export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

export const LOAD_MORE_ARTICLES_START = 'LOAD_MORE_ARTICLES_START';
export const LOAD_MORE_ARTICLES_SUCCESS = 'LOAD_MORE_ARTICLES_SUCCESS';
export const LOAD_MORE_ARTICLES_FAILURE = 'LOAD_MORE_ARTICLES_FAILURE';

export const FETCH_ARTICLE_BY_ID_START = 'FETCH_ARTICLE_BY_ID_START';
export const FETCH_ARTICLE_BY_ID_SUCCESS = 'FETCH_ARTICLE_BY_ID_SUCCESS';
export const FETCH_ARTICLE_BY_ID_FAILURE = 'FETCH_ARTICLE_BY_ID_FAILURE';
