export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

export const LOAD_MORE_ARTICLES_START = 'LOAD_MORE_ARTICLES_START';
export const LOAD_MORE_ARTICLES_SUCCESS = 'LOAD_MORE_ARTICLES_SUCCESS';
export const LOAD_MORE_ARTICLES_FAILURE = 'LOAD_MORE_ARTICLES_FAILURE';

export const FETCH_ARTICLE_BY_ID_START = 'FETCH_ARTICLE_BY_ID_START';
export const FETCH_ARTICLE_BY_ID_SUCCESS = 'FETCH_ARTICLE_BY_ID_SUCCESS';
export const FETCH_ARTICLE_BY_ID_FAILURE = 'FETCH_ARTICLE_BY_ID_FAILURE';

export const ADD_ARTICLE_TO_BASKET = 'ADD_ARTICLE_TO_BASKET';

export const SEARCH_ARTICLE = 'SEARCH_ARTICLE';

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
